In [6]:
import numpy as np

x = [12, 13,100, 36.32]
npx = np.array(x)
print(npx)

[ 12.    13.   100.    36.32]


In [23]:
x = np.arange(2,11).reshape((3,3))
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [19]:
x4 = np.zeros(10)
print(x4) 
x4[6] = 11
print(x4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [21]:
x5 = np.arange(12,39)
print(x5)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [26]:
x6 = np.arange(12,38)
print(x6)
x6 = x6[::-1]
print(x6)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
x